# Generated by Django 2.1.7 on 2019-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('host', models.CharField(max_length=200, verbose_name='host')),
                ('port', models.CharField(max_length=200, verbose_name='port')),
                ('user', models.CharField(max_length=200, verbose_name='user')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('db', models.CharField(max_length=200, verbose_name='db')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Dbs',
                'verbose_name_plural': 'Dbs',
            },
        ),
    ]
