# Generated by Django 2.1.7 on 2019-05-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('remark', models.CharField(max_length=200, verbose_name='remark')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200, verbose_name='project_id')),
                ('version_no', models.CharField(max_length=200, verbose_name='version_no')),
                ('summary', models.CharField(max_length=600, verbose_name='summary')),
                ('detail', models.CharField(max_length=200, verbose_name='detail')),
                ('publish_date', models.CharField(max_length=200, verbose_name='publish_date')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'ProjectVersion',
                'verbose_name_plural': 'ProjectVersion',
            },
        ),
    ]
